- templates/interface.njk
When you generate service from openapi, if you have an inherited object the result code is:
```
type JoinResponse extends ApiResponse = {
'data'
?: JoinResponseData;
}
```
but it isn't a valid typescript code.
The valid one is:
```
type LoginResponse = ApiResponse & {
data?: LoginResponseData;
};
```
> Fix generating inherited object code

- src/serviceGenerator.ts
Seems the customClassName is defined but not used yet. But this is required in my case. I got all tags written with Chinese, that's horrible to import services with Chinese.
> add implementation for hook customClassName

- src/serviceGenerator.ts
```typescript
openAPI: [
{
requestLibPath: "import { request } from 'umi'",
// 或者使用在线的版本
schemaPath: 'http://localhost:3006/docs-json',
mock: false,
projectName: '.',
hook: {
customFunctionName(operationObject: OperationObject) {
const newOperationId = operationObject.operationId
?.replace(/controller/i, '')
.replace(/[-_ .](\w)/g, (_all, letter) => letter.toUpperCase());
operationObject.operationId = 'newOperationId';
return newOperationId;
},
},
},
],
```
```typescript
/** 文章列表 GET /api/article */
export async function ArticleFindAll(
// 叠加生成的Param类型 (非body参数swagger默认没有生成对象)
params: API.ArticleFindAllParams & {
// query
/** 当前页面 */
current?: number;
/** 页面数据量 */
pageSize?: number;
/** 排序 */
orderBy?: 'createTime' | 'like' | 'topicCount' | 'id';
/** 排序方式 */
order?: 'DESC' | 'ASC'; …
```
> fix:使用customFunctionName重新定义名称后，对应的typing.d.ts没有变更，导致类型报红

- src/index.ts
- src/serviceGenerator.ts
- templates/serviceController.njk
- test/test.js
增加自定义参数类型名称hook。
目前“叠加生成的Param类型”名称与函数名称相同，但是类型名称统一放在了namespace下面，很容易冲突。
比如`PetController.query`，就直接生成了`API.queryParams`类型，如果其他controller有同名的query函数，就会用这同一个类型名称。
一种解决办法是让后端改函数名，比如`PetController.queryPets`、`ShopController.queryShops`，而且还必须保证函数名全局唯一。另一种是将这些类型放在各自的模块里面。
但是都比较麻烦，所以可以考虑用hook的方式进行自定义，就可以生成类似`API.PetQueryParams`的名称，参考test/test.js
如果可行的话还需要在@umi/plugin-openapi 加上`customTypeName: joi.function()`验证。
> add customTypeName hook

- src/serviceGenerator.ts
- templates/serviceController.njk
undefinedParams会被相应的{funcationName}Params取代。
> 解决typing.d.ts文件种生成多个undefinedParams类型问题

- src/index.ts
- src/serviceGenerator.ts
- templates/interface.njk
枚举样式支持
```
// config
enumStyle?: 'string-literal' | 'enum'
```
```
// typings.d.ts eg.
// string-literal style
type StatusEnum = 'Active' | 'InActive'
// enum style
enum StatusEnum { 
Active = 'Active',
InActive = 'InActive'
}
```
我识别到的 enum style 优势和使用场景：
1、支持将enum.value作为对象的Key，用于table column
```
{
title: '类型',
dataIndex: nameof<ISearchCouponResponse>((x) => x.type),
valueType: 'select',
valueEnum: {
[CouponTypeEnumOfCoupon.Discount]: { text: '折扣券' },
[CouponTypeEnumOfCoupon.FullReduction]: { text: '满减券' },
[CouponTypeEnumOfCoupon.Shipping]: { text: '运费券' },
},
},
```
2、用于下拉选择的options的类型辅助，如果是string-literal，无法及时发现枚举值变更(除非声明一个中间变量)
```
<ProFormRadio.Group
name="type"
label="优惠券类型"
initialValue={CouponTypeEnumOfCoupon.FullReduction}
options={[
{ value: …
```
> feat: #55 enumStyle support

- templates/interface.njk
#66
AuditFields作为审计字段被Car继承，此时生成的Car错误
```
// 错误示例
declare namespace API {
type AuditFields = {
lastUpdatedOn?: string;
createdOn?: string;
};
type Car = {
""?: AuditFields;
} & {
no: string;
name?: string;
userInfo?: UserInfo;
};
type UserInfo = {
id?: string;
name?: string;
};
}
```
```
// 正确示例
declare namespace API {
type AuditFields = {
lastUpdatedOn?: string;
createdOn?: string;
};
type Car = AuditFields & {
no: string;
name?: string;
userInfo?: UserInfo;
};
type UserInfo = {
id?: string;
name?: string;
};
}
```
> fix: generate IntersectionTypes by inherited class

- src/serviceGenerator.ts
主要做了类型名typeName 和 属性名称的兼容。比如：
```ts
“/user/:name”: {
res: {
3d_view_url: '...'
}
}
```
这种path和参数将生成
```ts
type getUserBy:nameParams = { }; // 错误
type RespUser = {
3d_view_url: '...'  // 错误
}
```
修改后：
```ts
type getUserByNameParams = { }; // 正确 
type RespUser = {
‘3d_view_url’: '...'  // 正确
}
```
> fix 兼容错误的属性和类型名

- src/serviceGenerator.ts
- test/example-files/swagger-schema-contain-blank-symbol.json
- test/test.js
schema 为这样的
*修改之前生成的 type name*
*修改之后生成的 type name*
> 解决 swagger 的 schema 中包含空格等特殊字符时生成的 type name 包含空格

- src/serviceGenerator.ts
当model名称是number开头的时候，ts会报错。这种场景一般发生在后端定义的名称是中文
上一个PR的正则， 只解决只处理了10以内的，超过10个中文依旧无法解析问题
> fix: (serviceGenerator.ts) 解决原正则只处理了10以内的，超过10个中文依旧无法解析问题

- templates/interface.njk
```
"AuthLogout": {"type": "object", "properties": {}}
```
before
after
> fix: 类型属性为空时的错误

- README.md
- src/index.ts
- src/serviceGenerator.ts
后端swagger文档中response返回的是包含统一的结构体，比如
```
{
"success": true,
"error": "",
"data": xxxxxx
}
```
但是前端工程中会在请求中进行封装统一返回数据字段，在业务代码中实际请求拿到的数据即为data字段数据，但是目前`openapi2typescript`中是原封不动还原swagger 文档中的response，直接使用会导致类型提示和运行结果不一致的问题
新增`dataFields`配置，拿到response中的数据字段
> feat: support data fields config

- src/util.ts
See https://github.com/umijs/umi/issues/10645
这解决了 esm 模块预加载过程中，没使用到这个函数，但是仍然加载了 prettier 这个较重的依赖耗费的时间瓶颈问题。
> perf: improve import perf

- package.json
- pnpm-lock.yaml
- src/serviceGenerator.ts
- test/example-files/swgger3.0.1.json
- test/test.ts
- 修复get等方法类型标注时，会将header参数放入params
- 添加windows的ts测试，方便调试
- 新增devDependencies的 tslib包，是测试时无法ts-node运行报错缺少包
注：上一次的headr的修复并不完整，这次我将测试用例添加到文件了。以下我会展示之前的问题是什么？↓↓↓↓↓↓
包版本：
swgger文件：
生成的结果：
> 🐛 fix: 修复get等方法类型标注时，会将header参数放入params 💥 feat: 添加windows的ts测试

- src/serviceGenerator.ts
修复将header参数放入params的功能#111，未兼容operationObject.parameters可能为空的情况，导致报错，影响正常使用
报错如下：
/Users/alexander/code/create-vite-react-app/node_modules/.pnpm/@umijs+openapi@1.8.4/node_modules/@umijs/openapi/dist/serviceGenerator.js:560
Object.keys(this.openAPIData.paths || {}).forEach((p) => {
^
TypeError: Cannot read properties of undefined (reading 'filter')
at /Users/alexander/code/create-vite-react-app/node_modules/.pnpm/@umijs+openapi@1.8.4/node_modules/@umijs/openapi/dist/serviceGenerator.js:567:73
at Array.forEach (<anonymous>)
at /Users/alexander/code/create-vite-react-app/node_modules/.pnpm/@umijs+openapi@1.8.4/node_modules/@umijs/openapi/dist/serviceGenerator.js:562:55
at Array.forEach (<anonymous>)
at ServiceGenerator.getInterfaceTP …
> fix: 修复operationObject.parameters可能为空导致报错

- package.json
- src/serviceGenerator.ts
- test/example-files/swagger-custom-hook.json
生成API注释时，增加了应答的默认描述，以看到对返回值的说明。顺便解决了运行 npm run test:windows 时的问题。
修改前：
/** 登录 - 帐密登录 参数：account POST /api/v1/user/account/login.json */
export async function accountLogin(body: API.AccountLoginReq, options?: { [key: string]: any }) {
修改后：
/** 登录 - 帐密登录 参数：account 返回值: true代表登录成功，否则为提示信息 POST /api/v1/user/account/login.json */
export async function accountLogin(body: API.AccountLoginReq, options?: { [key: string]: any }) {
> API注释中增加应答的默认描述

- src/serviceGenerator.ts
> pref: 生成的ts文件名和api函数改为驼峰命名

- src/serviceGenerator.ts
fixed bug: [#122](https://github.com/chenshuai2144/openapi2typescript/issues/122)
> fix: 修复requestBody中properties属性键值存在特殊符号导致报错解析文件失败

- README.md
- src/index.ts
- src/serviceGenerator.ts
强制小驼峰命名未考虑历史包袱，未考虑使用者的迁移意愿，遂加入新参数isCamelCase。
默认为小驼峰命名，不愿迁移的使用者使用isCamelCase: false保持默认命名
> perf: 新增isCamelCase参数, 支持小驼峰命名或者默认命名

- README.md
- src/index.ts
- src/serviceGenerator.ts
- templates/serviceController.njk
resolve #83
目前 `options` 的类型在模板里面是写死为 `{[key: string]: any}`的，希望 `options` 的ts类型变为可配置项。例如：
> feat: support requestOptionsType config

- src/serviceGenerator.ts
media为application/x-www-form-urlencoded时也含有form，但是不应该使用formData
> fix: application/x-www-form-urlencoded不适用formData传参

- README.md
- src/serviceGenerator.ts
这个PR改回了int64转换为string的改动, 并在README添加了hook的相关文档.
Int64还是数字类型, 默认转换为string类型很奇怪. 即使定义的是int64, 前端在操作这个数据时也是按照number类型来处理, 只是需要注意数据溢出处理. 而不是改成字符串.
如果确实需要对int64处理为BigInt或者string类型的, 是不是也可以使用`customTypeName` 这个hook来完成? 不知道是不是有伙伴不知道这些hook的存在，所以把这部分文档抽取出来了。
相关讨论.
https://github.com/chenshuai2144/openapi2typescript/issues/131
> 回退默认把int64转换为string的修改

- src/serviceGenerator.ts
使用apifox生成的openapi3.1的接口时，下面这种情况required判断不正确
> fix: required在schemaObject和properties中的情况

- src/index.ts
将其应用在热更新的环境时,require的缓存会导致读取不到最新变更的json内容
> fix: 消除require的缓存

- README.md
- package.json
- pnpm-lock.yaml
- src/cli.ts
这个pr主要包含两个点：
1. 当前的使用方式需要由本地的`ts-node` 执行代码，但实际项目中，经常没有`ts-node`或者 `tsx` 这类依赖， 直接支持 cli 配合读取项目的配置文件应该是一个更好的使用方式。
2. 配置文件中以数组的方式支持同时配置多个 openapi endpoint，满足项目可能同时对接多个服务的场景。
不确定 **openapi2ts** 这个cli 的命令是否合适，欢迎讨论。
> 增加 Cli 以及项目级别配置文件支持

- .prettierrc.js
- package.json
- pnpm-lock.yaml
- src/mockGenerator.ts
- src/util.ts
当前项目生成文件时，使用的 prettier 配置来自于 ```@umijs/fabric```，导致两个小问题：
1. 默认的 prettier 配置与引用项目实际使用的配置可能不符，需要二次格式化；
2. 导致较多的次级依赖，比如vscode 项目打开时，始终提示stylelint 13 升级14 的警告；
该PR移除了 ```@umijs/fabric```依赖，将其prettier配置部分添加到项目的.prettierrc.js配置文件中；生成文件时，加载工作目录下的 prettier 配置，对生成的文件进行格式化。
> 解析工作项目的prettier配置进行格式化
