src/serviceGenerator.ts
fix generation of source when you have a file parameter.
When you have a file to upload, it is represented by a parameter in the body in binary or base64 format.
=> fix upload file

src/serviceGenerator.ts
path parameters can be omitted in declaration
=> parse not declared path params

src/serviceGenerator.ts
=> 修复'生成的api文件中的请求方法第一个参数必定是params，即使没有定义path参数和query参数'的问题

src/serviceGenerator.ts
=> fix #13 and fix resolveTypeName func check chinese bug.

src/serviceGenerator.ts
1.  无operationId时，给默认functionName
2. 修复文件名存在中文的bug
=>  无operationId时，给默认functionName

src/mockGenerator.ts, src/serviceGenerator.ts, templates/interface.njk
1. fix bug: 当body为json时,没有任何一个 required，导致 `Cannot read property includes of undefined`
2. fix bug : [ant-design-pro/9159](https://github.com/ant-design/ant-design-pro/issues/9159)
3. fix bug : allof 问题导致结构非预期。
=> fix bug: required、mock path parameters、allof one  parameter

.gitignore, package.json, templates/serviceController.njk, test/example-files/swagger-file-convert.json, test/example-files/swagger-get-method-params-convert-obj.json, test/test.js
修复文件上传接口的转换
close https://github.com/ant-design/ant-design-pro/issues/9080
https://github.com/umijs/umi-request/blob/HEAD/README_zh-CN.md#%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0
=> fix: file type convert ant-design/ant-design-pro#9080

src/serviceGenerator.ts, templates/serviceController.njk
改动的不多，大部分都是格式化的代码😂
close ant-design/ant-design-pro#9293
=> fix: 修复路由参数声明在path中导致未生成Params类型的问题，修复Params模板中重复定义的问题

src/index.ts, src/serviceGenerator.ts
用户可以自定义修改模板
```
const { generateService } = require('@umijs/openapi')
generateService({
requestLibPath: "import { Request as request } from 'umi'",
schemaPath: 'http://petstore.swagger.io/v2/swagger.json',
serversPath: './servers',
templatesFolder: './templates'
})
```
=> feature: 添加自定义模板文件路径选项

templates/serviceController.njk
=> fix: 修复header部分生成异常

src/serviceGenerator.ts
=> fix: generate array of enums

src/serviceGenerator.ts
=> quick fix issue #41

src/index.ts, templates/serviceController.njk
fix: 修复https fetch导致 http文档地址无法生成的问题[#46](https://github.com/chenshuai2144/openapi2typescript/issues/46)
=> fix: 修复fetch导致 http文档地址无法生成的问题

templates/interface.njk
=> fix: #59 property missing when props.length == 1

src/index.ts, templates/serviceController.njk
当mediaType为 multipart/form-data时，仍生成了Content-Type
=> fix: mediaType判断错误

README.md, src/index.ts
=> doc: 更新文档描述

templates/interface.njk
=> remove if statement

src/serviceGenerator.ts, templates/serviceController.njk
加了customTypeName就是为了解决这个问题的，1.4的版本还能用，麻烦审核一下，谢谢
=> fix: params name conflict #40 #56

.eslintrc.js, package.json, tsconfig.json
=> fix: eslint version

README.md, src/index.ts, src/serviceGenerator.ts, templates/interface.njk, test/test.js
后端实际上是以null作为默认值，而不是undefined，使用nullable可以配置使用null代替?:
=> feat: 支持null代替?:

.gitignore, templates/interface.njk, test/test-allof-api.json, test/test.js
https://github.com/chenshuai2144/openapi2typescript/issues/89
当Prop只有一个，并且有 `$ref` 属性时，省略前后的大括号和字段名称，从而生成复合Typescript语法的类型申明。
=> Check $ref properties (#89)

src/serviceGenerator.ts
=> fix: remove header in params

src/serviceGenerator.ts
fix  https://github.com/ant-design/ant-design-pro/issues/10840
=> fix: 解决扩展属性没有追加到生成对象中的问题

package.json, test/test.js
1.增加isCamelCase属性功能相关的测试用例
2.根据测试代码生成目录优化一下代码顺序
3.修复test script命令报错的bug
=> feat: 增加isCamelCase属性功能相关的测试用例

src/serviceGenerator.ts, test/example-files/swagger-empty.json, test/test.js
=> fix: 解决JSON中components.schemas为空导致的生成报错
